default_install_hook_types:
  - pre-commit
  - commit-msg
default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
        exclude: \.vscode/|\.devcontainer/
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: detect-private-key
      - id: debug-statements
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.9
    hooks:
      - id: ruff-check
        args: [--fix, --output-format=full]
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.30.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "6.0"]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          - --strict
          - feat
          - fix
          - chore
          - docs
          - style
          - refactor
          - perf
          - test
          - build
          - ci
          - revert
          - wip